---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - include: install_package.yml
    with_items: '{{ common_software }}'

  - include: install_package.yml
    with_items: '{{ server_software }}'

  vars_files:
    - vars/main.yml
